### ISSUE TITLE
Add Planner Tasks and Todos

### ISSUE THREAD

**Issue by lauer** [NEXL-LTS/ms_graph_rest-ruby#12]
Hi, Thanks for sharing your implementation.

I need to access a user's todo and planner tasks from a rails app. So I have been working on a small extension.
It's still missing some rspec tests, but when that is done, I will create a PR. 

Is it okay to have simple implementation first? And would you accept the PR after review?

**Comment by bapu-nexl** [comment]
Thanks for adding this. I am happy if @grantspeelman  is ok.
