### ISSUE TITLE
Rails 7 support? 

### ISSUE THREAD

**Issue by DanielRoende** [NEXL-LTS/ms_graph_rest-ruby#18]
Hey. 

I'm getting this dependency error: 

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
  
  ms_graph_rest was resolved to 0.1.0, which depends on
      activesupport (>= 3.2, < 7.0)

    rails (~> 7.0.1) was resolved to 7.0.1, which depends on
      activesupport (= 7.0.1)

Tried setting activesupport versions to no avail 

Any tips or tricks ?

**Comment by grantspeelman** [comment]
thanks sharing

removed the activesupport dependency https://github.com/NEXL-LTS/ms_graph_rest-ruby/commit/19564a4beb69f1ef64c67b66b05db3053ae2379c
So it should work now
